# ABOUTME: Gem dependencies for the Janus home-climate dashboard backend.
# ABOUTME: Sinatra app + DuckDB storage + SensorPush client; minitest for tests.

source "https://rubygems.org"

ruby "~> 4.0"

gem "sinatra", "~> 4"
gem "rackup"
gem "puma"
gem "duckdb"
# From the tagged GitHub release until 0.2.0 is published to RubyGems.
gem "sensorpush", git: "https://github.com/michellepellon/sensorpush.rb", tag: "v0.2.0"
gem "dotenv"
gem "rake"

group :test do
  gem "minitest"
  gem "rack-test"
end
